image: microsoft/dotnet:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build DutchPurpleFiat/DutchPurpleFiat.sln"
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - "dotnet test DutchPurpleFiat/DutchPurpleFiat.sln"
